sonar.projectKey=Lessorus_frontend-project-46
sonar.organization=lessorus

# Пути к коду и тестам
sonar.sources=src
sonar.tests=__tests__

# Чтобы SonarCloud видел покрытие тестами
sonar.javascript.lcov.reportPaths=coverage/lcov.info
